### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by adhilsalim** [incial/intern-hub#39]
@ABIN-VARGHEXE 

improve the UI, such as text and image alignments, position etc.

use `ih-aow` as the id for area of work section

**Comment by adhilsalim** [comment]
1. If possible, change the icon color in the Long Term Support System section. 
2. Add a `br` tag to fix the misalignment in the Areas of Work section.
3. fix the drop down arrows in Areas of work section.

**Comment by ABIN-VARGHEXE** [comment]
1. colour changed 
2. padding fixed
3. drop was already ok @adhilsalim check the merge
